export const INCREMENT_STEP = "INCREMENT_STEP";
export const DECREMENT_STEP = "DECREMENT_STEP";

export const ADD_LABEL = "ADD_LABEL";
export const MODIFY_LABEL = "MODIFY_LABEL";
export const DELETE_LABEL = "DELETE_LABEL";
export const SET_ACTIVE_LABEL_ID = "SET_ACTIVE_LABEL_ID";

export const ADD_LABEL_TYPE = "ADD_LABEL_TYPE";
export const DELETE_LABEL_TYPE = "DELETE_LABEL_TYPE";
export const SET_ACTIVE_LABEL_TYPE_ID = "SET_ACTIVE_LABEL_TYPE_ID";

export const ADD_FILE = "ADD_FILE";
